django_level_four/learning_templates/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns= [
   path('relative/',views.relative,name='relative'),
   path('other/',views.other,name='other'),
]

django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    
]

django_level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

django_level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)


def other(request):
    return render(request,'basic_app/other.html')



def relative(request):
    return render(request,'basic_app/relative_url_template.html')

django_level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE PAGE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light"style= background-color: #e3f2fd;>   
            <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'admin:index' %}">ADMIN <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic_app:other' %}">OTHER</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="{% url 'basic_app:relative' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    RELATIVE
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
        
    </nav>
    <div class="container">
        {% block body_block%}

        {% endblock %}
    </div>

    
</body>
</html>






    

django_level_four/learning_templates/templates/basic_app/index.html
{% extends "basic_app/base.html"%}
    {% block body_block %}

    <h1>Wellcome TO INDEX PAGE </h1>

    <h2>{{ text|cut:'hello'|upper }}</h2>
    <h2>{{ number|add:1 }}</h2>
  
    {% endblock %}

django_level_four/learning_templates/templates/basic_app/other.html
{% extends "basic_app/base.html"%}
    {% block body_block %}


    <h1>Wellcome to OTHER page</h1>
    <h2>Example of template inheritance</h2>

    {% endblock %}

django_level_four/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RELATIVE PAGE</title>
</head>
<body>
    <h1>Wellcome to Relative page</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a> -->
    <a href="{% url 'admin:index' %}">LINK TO ADMIN PAGE</a>
    <a href="{% url 'index' %}">INDEX PAGE</a>
</body>
</html>